# Generated by Django 5.2.9 on 2026-01-21 18:25

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media', '0003_alter_media_media_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMediaList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('PTS', 'PLAN TO START'), ('PRG', 'IN PROGRESS'), ('COM', 'COMPLETED'), ('ONH', 'ON HOLD'), ('DRP', 'DROPPED')], default='PTS', max_length=3, verbose_name='Status')),
                ('rating', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('review', models.TextField(blank=True, max_length=1000, verbose_name="User's Review")),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracked_by', to='media.media')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_collection', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'media'), name='user_unique_movie')],
            },
        ),
    ]
