# Generated by Django 5.2.11 on 2026-02-10 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('creator', models.CharField(max_length=255, verbose_name='Creator')),
                ('summary', models.TextField(blank=True, max_length=1000, verbose_name='Summary')),
                ('media_type', models.CharField(choices=[('AN', 'ANIME'), ('MV', 'MOVIE'), ('SR', 'SERIES'), ('BK', 'BOOK'), ('AL', 'ALBUM'), ('GM', 'GAME')], default='MV', max_length=2)),
                ('release_date', models.SmallIntegerField(blank=True, null=True, verbose_name='Release Date')),
                ('cover', models.URLField(blank=True, null=True, verbose_name='URL Cover')),
                ('external_id', models.CharField(db_index=True, max_length=255, unique=True, verbose_name="API Id's")),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
